### ISSUE TITLE
Manage/Use Views

### ISSUE THREAD

**Issue by dc0d** [flimzy/kivik#138]
How to manage & use views?

- Creating Design Documents,
- Creating views (map/reduce functions),
- Query views (range keys, array keys, ...),
- Reduce/Not-Reduce views,

**Comment by flimzy** [comment]
I'll work on updating the wiki with detailed information on these points when I have time. The short answers follow:

> - Creating Design Documents,

The same way you create a normal document, but with the proper name.  I.e. by using [`Put`](https://godoc.org/github.com/flimzy/kivik#DB.Put):  `db.Put(context.TODO(), "_design/foo", map[string]interface{}{ "_id": "_design/foo", ...} )`

> - Creating views (map/reduce functions),

When creating/updating the design document, include the view/reduce functions [normally](https://wiki.apache.org/couchdb/HTTP_view_API#Creating_Views).

    db.Put(context.TODO(), "_design/foo", map[string]interface{}{
        "_id": "_design/foo",
       "views": map[string]interface{}{
            "foo_view": map[string]interface{}{
                "view": "function(doc) { ... }",
            },
        },
    })

> - Query views (range keys, array keys, ...),

Use the [`Query`](https://godoc.org/github.com/flimzy/kivik#DB.Query) method.

> - Reduce/Not-Reduce views,

Also with [`Query`](Reduce/Not-Reduce views,).  To use the `reduce` function, pass a `"group": true` option:

    db.Query(context.TODO(), "foo", "foo_view", map[string]interface{}{"group": true})

**Comment by flimzy** [comment]
I have now updated the wiki with answers to these questions, so will close this issue.

 - [Creating Design Documents](https://github.com/flimzy/kivik/wiki/Usage-Examples#design-documents)
- [Creating views (map/reduce functions)](https://github.com/flimzy/kivik/wiki/Usage-Examples#create-or-update-a-view)
- [Query views (range keys, array keys, ...)](https://github.com/flimzy/kivik/wiki/Usage-Examples#query-a-view)
- [Reduce/Not-Reduce views](https://github.com/flimzy/kivik/wiki/Usage-Examples#mapreduce)
