### ISSUE TITLE
CouchDB _find responses could have a warning key

### ISSUE THREAD

**Issue by fschndr** [flimzy/kivik#139]
I recently messed around with _find and indexes. I accidentally produced a query with an miss matching index. 
The error returned by ScanDoc() is `Iterator is closed`
Err() gives me `Unexpected key: warning`

I popped the query into my GUI REST client and the warning looks like this:

```
{
	"warning": "no matching index found, create an index to optimize query time",
	"docs": [
		{
...
```

For now this is the only warning in mango queries:
http://docs.couchdb.org/en/2.0.0/api/database/find.html#creating-selector-expressions  

https://github.com/apache/couchdb/blob/f4c6113808d1809469df9c8be9d2f83ef399f064/src/mango/src/mango_httpd.erl#L235

I guess it would be good to expect possible warnings and let them surface anyhow. Maybe store them in a warning type - so you could retrieve it like Err().

Kind Regards

Fabian

**Comment by flimzy** [comment]
Thank you for the bug report. I believe the problem is now solved. Please let me know if you discover otherwise!
