### ISSUE TITLE
db.put document without predefined _id

### ISSUE THREAD

**Issue by SerkanSipahi** [flimzy/kivik#198]
How can i put a document without predefined _id? 
What i want is that the _id should be generated by couch!
 
```shell
curl -H 'Content-Type: application/json' \
            -X POST http://127.0.0.1:5984/demo \
            -d '{"company": "Example, Inc."}'
```

How can i resolve this with kivik? 

When i use db.Put and pass empty string as second parameter (DocId) it occurs an error `panic: Unauthorized: You are not a server admin.`.

Must i be authorized when i put a document without _id? (with _id no error occurs)

**Comment by flimzy** [comment]
> How can i put a document without predefined _id?

Use [CreateDoc](https://godoc.org/github.com/flimzy/kivik#DB.CreateDoc).

> Must i be authorized when i put a document without _id? (with _id no error occurs)

This depends on your database security settings. I refer you to the [CouchDB Security](http://docs.couchdb.org/en/2.0.0/intro/security.html) documentation.

**Comment by SerkanSipahi** [comment]
>Use CreateDoc.

thanks

>This depends on your database security settings. I refer you to the CouchDB Security documentation.

I know, but what i mean was that when i used db.put with empty("") DocId its panic (see above)

**Comment by flimzy** [comment]
> when i used db.put with empty("") DocId its panic

Hmm, can you show me your Go code that's producing the panic?  My attempts to reproduce return an error rather than a panic.

**Comment by SerkanSipahi** [comment]
This is the correct error message when the _id is empty:
command: 
```bash
curl -H 'Content-Type: application/json'
-X POST http://127.0.0.1:5984/honeyglass
-d '{"_id": "","company": "Example, Inc."}'
```
result:
```json
{"error":"illegal_docid","reason":"Document id must not be empty"}
```

This panic with kivik:
```golang
func main() {
	client, err := kivik.New(context.TODO(), "couch", "http://localhost:5984/")
	if err != nil {
		panic(err)
	}

	db, err := client.DB(context.TODO(), "mydb")
	if err != nil {
		panic(err)
	}

	doc := map[string]interface{}{
		"feet":     4,
		"greeting": "moo",
	}

	rev, err := db.Put(context.TODO(), "", doc)
	if err != nil {
		panic(err)
	}
	fmt.Printf("Cow inserted with revision %s\n", rev)
}
```
```error
panic: Unauthorized: You are not a server admin.
```

**Comment by flimzy** [comment]
I see, the panic is from your code... you're just asking about the difference in error message.

The difference is because the `Put()` method does a `PUT` not a `POST`.  You can reproduce the same with curl, as well:

    curl -H 'Content-Type: application/json' -X PUT http://127.0.0.1:5984/honeyglass -d '{"_id":"","company":"Example, Inc."}'
    {"error":"unauthorized","reason":"You are not a server admin."}

**Comment by SerkanSipahi** [comment]
thanks for the difference. Im very very new with couch! sometimes im blind :(

**Comment by SerkanSipahi** [comment]
https://wiki.apache.org/couchdb/HTTP_Document_API#PUT: the reason why "You are not a server admin" appears is that when you use "put" and and assign an empty string to the query look like this /somedatabase instead of /somedatabase/some_doc_id

**Comment by flimzy** [comment]
> the reason why "You are not a server admin" appears is that when you use "put" and assign an empty string to _id, kivik reproduce a query like this: /somedatabase instead of: /somedatabase/some_doc_id !

Yes, that's exactly right... CouchDB interprets that as an attempt to create a new database, rather than a new document.

I'll consider how best to improve the error reporting in Kivik for this situation.  Thanks for bringing my attention to the issue.

**Comment by SerkanSipahi** [comment]
btw, the code thats panic its copied from kivik README.md, the only difference is the empty string :)

**Comment by SerkanSipahi** [comment]
its reopen due

>I'll consider how best to improve the error reporting in Kivik for this situation. Thanks for bringing my attention to the issue.

please give the issue a tag.

**Comment by flimzy** [comment]
I have opened https://github.com/go-kivik/couchdb/issues/3 to address this issue in the CouchDB driver.
