### ISSUE TITLE
kivik: driver does not support sessions

### ISSUE THREAD

**Issue by SerkanSipahi** [flimzy/kivik#199]
1. Which version of Kivik are you using?
>v1.1.0

2. Which version of Go are you using? (Output of `go version`) -- Kivik 1.0 aims to support all versions of Go from 1.7
>v1.9

3. What did you do? 
```golang
err = client.Authenticate(context.TODO(), &chttp.CookieAuth{
	Username: "user",
	Password: "foo",
})
fmt.Println(err) // log: <nil>

session, err := client.Session(context.TODO())
fmt.Println(session, err) // log: <nil> kivik: driver does not support sessions
```
4. What did you expect to see?
Session should have "RawResponse" member which contain additional fields with an "Token"

5. What did you see instead?
Log: kivik: driver does not support sessions. 
It seems this feature is not implemented https://github.com/flimzy/kivik/blob/325bae4e7ca4f19e39d6d539aacb21044517624c/session.go#L41 or im doing something wrong.

----------

Using with kivik: How can i read/retrieve the cookie token with kivik after Authenticated and how can i use it for the next authentication?

**Comment by SerkanSipahi** [comment]
Its seems kivik is in some things very complicated, or im to ... :( I do lot of reverse engineering.

**Comment by SerkanSipahi** [comment]
What i want to achieve is, pass the Cookie from `kivik.Client.Authenticate` to the Browser and of course vice versa from the browser to kivik back for authenficate itself with the token.

**Comment by flimzy** [comment]
1. As the error indicates, the driver you're using does not support fetching sessions. Which driver are you using?

2. There's no way to get the session cookie from Kivik. I have never thought of a need for this. What is your use case?

**Comment by SerkanSipahi** [comment]
1.) i use the standard couch driver`client, err := kivik.New(context.TODO(), 'couch', 'http://localhost:5984/')`
2.) There is a api url on client (browser) like /login. With that url you can post your credentials (username, password). If everything works well, you get an auth token that can be use for e.g. critical areas. Any idea how can I achieve this?

**Comment by SerkanSipahi** [comment]
Or can i couple/link/connect a kivik.handler to an `http.Handle("/login", kivik.Handler.auth.handler)` where can i write the cookie-auth infos to the response object?

**Comment by SerkanSipahi** [comment]
How can i do this with kivik:
#### Request
```bash
> HOST="http://127.0.0.1:5984"
> curl -vX POST $HOST/_session -H 'application/x-www-form-urlencoded' -d 'name=foo&password=secret'
```
#### Response
```bash
< HTTP/1.1 200 OK
< Set-Cookie: AuthSession=YW5uYTo0QUIzOTdFQjrC4ipN-D-53hw1sJepVzcVxnriEw;
< Version=1; Path=/; HttpOnly
> ...
<
{"ok":true}
```

#### Request (with only token without using of "name" and "password" again)
```bash
> curl -vX PUT $HOST/mydatabase --cookie AuthSession=YW5uYTo0QUIzOTdFQjrC4ipN-D-53hw1sJepVzcVxnriEw -H "X-CouchDB-WWW-Authenticate: Cookie" -H "Content-Type: application/x-www-form-urlencoded"
{"ok":true}
```

**Comment by flimzy** [comment]
1. I have just published [v1.0.6](https://github.com/go-kivik/couchdb/releases/tag/v1.0.6) of the CouchDB driver--I had the Session support sitting in an unmerged PR. It's now merged.

2. If your only goal is to know if a token is valid, then fetching the Session, as you are attempting to do, is indeed the best way.

If you actually need the session cookie, there's no easy way to get at the session cookie directly at the moment. Let me ponder this a while, and see if I can think of an elegant solution.

**Comment by SerkanSipahi** [comment]
1.) Thank you. "Kivik: driver does not support sessions" has disappeared. The session.RawResponse looks good after logged in. All useful informations e.g. "roles", name, etc are there: 
```json
{
  "ok": true,
  "userCtx": {
    "name": "foo",
    "roles": [
      "_admin"
    ]
  },
  "info": {
    "authentication_db": "_users",
    "authentication_handlers": [
      "cookie",
      "default"
    ],
    "authenticated": "cookie"
  }
}
```
2.) What do you mean?
>If your only goal is to know if a token is valid, then fetching the Session, as you are attempting to do, is indeed the best way.

3.) This will be really really nice. The best place for that would be in RawResponse. 
>If you actually need the session cookie, there's no easy way to get at the session cookie directly at the moment. Let me ponder this a while, and see if I can think of an elegant solution.

Note: i could help you if that ok. I can write examples for Kivik or something different. Please tell if you need help.

**Comment by SerkanSipahi** [comment]
It will be good when we convert the json(seesion. RawResponse) to struct with json.unmarshal for better accessing and auto completion within the IDE´s.

**Comment by SerkanSipahi** [comment]
Additions to 3.) It will be good when there something like this for authentication with an token:
```golang
tokenAuth := chttp.TokenAuth{
	Token: "sdfkjksw94ajslasdflaksjfölasdf"
}
err = client.Authenticate(context.TODO(), &tokenAuth)
```

**Comment by flimzy** [comment]
> 2.) What do you mean? I can only fetching Session when im logged before. Do mean that?

Essentially, yes. By fetching the session, you can validate that the user you expected to be authenticated is indeed authenticated.

> 3.) This will be really really nice. The best place for that would be in RawResponse.

`RawResponse` is the raw JSON body returned by the server. Putting HTTP headers in there would fundamentally change the meaning, format, and schematic of that data. I'm not going to do that.

I think the best way to accomplish this is to expose the underlying HTTP transport (and thus its CookieJar). But it's not entirely obvious how to accomplish this in a streamlined way, so I'll need to put additional thought into how to accomplish that.

**Comment by flimzy** [comment]
> Additions to 3.) It will be good when there something like this for authentication with an token:

An auth method that takes a raw cookie value is not a bad idea, and probably not difficult to implement.  I'll try to do that, too. Thanks for the suggestion.

**Comment by SerkanSipahi** [comment]
What about this?

>I think the best way to accomplish this is to expose the underlying HTTP transport (and thus its CookieJar). But it's not entirely obvious how to accomplish this in a streamlined way, so I'll need to put additional thought into how to accomplish that.

```golang
cookieAuth := &chttp.CookieAuth{
	Username: "user",
	Password: "foo",
})
var string authSession
err = client.Authenticate(context.TODO(), cookieAuth, func(w http.ResponseWriter, r *http.Request) {
    authSession, _ := r.Cookie("AuthSession")
})
```

**Comment by flimzy** [comment]
It should now be possible to access the CouchDB session cookie.  For example:

```go
auth := &chttp.CookieAuth{
	Username: "user",
	Password: "foo",
}
if err := client.Authenticate(context.TODO(), auth); err != nil {
	panic(err)
}
var token string
if cookie, ok := auth.Cookie(); ok {
	token = cookie.Value()
}
```

**Comment by SerkanSipahi** [comment]
@flimzy thank you very much :)

**Comment by SerkanSipahi** [comment]
Do you resolve this feature in this issue?
>An auth method that takes a raw cookie value is not a bad idea, and probably not difficult to implement. I'll try to do that, too. Thanks for the suggestion.
```golang
tokenAuth := chttp.TokenAuth{
	Token: "sdfkjksw94ajslasdflaksjfölasdf"
}
err = client.Authenticate(context.TODO(), &tokenAuth)
```

Thank you

**Comment by flimzy** [comment]
No, I have not done that yet.

**Comment by SerkanSipahi** [comment]
there's no rush for `chttp.TokenAuth`, but that would complete the authentication function :)

**Comment by flimzy** [comment]
I have opened a new issue to track the `TokenAuth` request: https://github.com/go-kivik/couchdb/issues/8

**Comment by SerkanSipahi** [comment]
Thank you
