### ISSUE TITLE
Add server/proxy support for the _bulk_get endpoint

### ISSUE THREAD

**Issue by flimzy** [flimzy/kivik#205]
PouchDB and supports the _bulk_get endpoint documented [here](https://pouchdb.com/2015/10/06/pouchdb-5.0.0-five-years-of-pouchdb.html).  It would be nice to add support to the kivik server, and emulate it in proxy mode, especially for the benefit of PouchDB clients.

**Comment by flimzy** [comment]
Upon further investigation, I don't believe there's anything to add to Kivik here until it does its own replication.

**Comment by fungiboletus** [comment]
Hei, I think I need this feature in my project. It's designed for fast replication but I'm considering to implement it to fetch many documents in one single request.

**Comment by flimzy** [comment]
Are you using the kivik server or proxy functionality?  Or are you just saying you'd like **_bulk_get** support added to the Kivik library?

**Comment by fungiboletus** [comment]
No I'm not using the server or the proxy.  I have uses cases where I need
to load about 5 to 100 documents from their IDs so I wanted to use
_bulk_get for that.

I'm currently implementing it on my local fork, only for the CouchDB driver
though. The parsing is a bit more complex than expected, but it looks
doable.

Le mar. 15 janv. 2019 à 10:33, Jonathan Hall <notifications@github.com> a
écrit :

**Comment by fungiboletus** [comment]
I made two pull requests :

 * go-kivik/kivik#340
 * go-kivik/couchdb#138

It's based on the stable API and I didn't took the time to implement unit testing, so I will not be offended if you decide to ignore them, but it works for me.
