### ISSUE TITLE
Missing support for setting new_edits to false in BulkDocs

### ISSUE THREAD

**Issue by vladimiroff** [flimzy/kivik#208]
[`/db/_bulk_docs`](http://docs.couchdb.org/en/2.0.0/api/database/bulk-api.html#db-bulk-docs) accepts optional `new_edits` parameter in the request JSON object which if `false`, prevents the database from assigning new revision IDs (it's `true` by default).

There doesn't seem to be a way to set `new_edits` to `false`, judging by [how the request is being constructed](https://github.com/flimzy/kivik/blob/master/driver/couchdb/bulk.go#L65).

**Comment by flimzy** [comment]
Thank you for the report; this is clearly something that needs to be fixed. I'll try to get to this as soon as possible.

**Comment by flimzy** [comment]
I have released [v1.3.0](https://github.com/flimzy/kivik/releases/tag/v1.3.0) with the added support.

Thanks again for reporting the issue!
